version: "3.3"

services:
  app:
    image: inspectorio/prediction-io
    container_name: pio
    volumes:
    - ./:/home/pio/app/src
    - ~/.ssh:/home/pio/.ssh
    command:
    - /bin/bash
    - -c
    - 'trap : TERM INT; sleep infinity & wait'
    ports:
    - 9000:9000
    - 7070:7070
    environment:
      PIO_DB_HOST: postgres
      PIO_DB: pio
      PIO_DB_USER: pio
      PIO_DB_PASSWORD: pio
      ES_HOST: elasticsearch
      ES_PORT: 9200

  postgres:
    image: postgres:9.6
    container_name: pio-postgres
    environment:
      POSTGRES_USER: pio
      POSTGRES_PASSWORD: pio
      POSTGRES_DB: pio

  elasticsearch:
    container_name: pio-es
    image: inspectorio/elasticsearch-without-xpack
